[package]
name = "lunarbase-client-arbitrum"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
description = "Experimental Arbitrum Nitro runtime client for LunarBase"

[lints]
workspace = true

[dependencies]
lunarbase-client-core.workspace = true
