[package]
name = "lunarbase-client"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
description = "Compatibility facade for all LunarBase Rust runtime clients"

[lints]
workspace = true

[dependencies]
lunarbase-client-arbitrum.workspace = true
lunarbase-client-base.workspace = true
lunarbase-client-core.workspace = true
lunarbase-client-monad.workspace = true
