import { QuoteError, assertU256, type Address } from "./constants.js";
import { checkedAdd, checkedSub } from "./arithmetic.js";
import { laneSlot0AskFeeBps, laneSlot0BidFeeBps, laneSlot0LatestUpdateBlock, laneSlot0Price } from "./slot0.js";
import { calculateFeeBpsForRouter, quoteLaneExactIn, quoteLaneExactInFee, quoteLaneExactOut, quoteLaneExactOutFee, quoteLaneSlippageBps, quoteLaneWeightedSlippageKBps, splitFee } from "./fees.js";
import type { LaneState, QuoteContext, QuoteOutcome, QuoteRequest, QuoteResult, QuoteState, UnavailableReason } from "./types.js";

function feeKey(router: Address, asset: Address): string { return `${router.toLowerCase()}:${asset.toLowerCase()}`; }
function partnerFee(state: QuoteState, router: Address, asset: Address): bigint { return state.partnerFeeBps.get(feeKey(router, asset)) ?? 0n; }
function laneOrReason(state: QuoteState, asset: Address, context: QuoteContext): LaneState | UnavailableReason { const lane = state.lanes.get(asset); if (!lane || !lane.exists) return { kind: "MissingLane", asset }; if (lane.paused) return { kind: "PausedLane", asset }; const readyAt = checkedAdd(laneSlot0LatestUpdateBlock(lane.slot0), lane.blockDelay); if (context.executionBlockNumber < readyAt) return { kind: "DelayedLane", asset }; if (laneSlot0Price(lane.slot0) === 0n) return { kind: "ZeroPrice", asset }; return lane; }
function principalCashValue(state: QuoteState, asset: Address, lane: LaneState): bigint { const principal = state.totalPrincipalAmount.get(asset) ?? 0n; return principal === 0n ? 0n : quoteLaneExactIn(laneSlot0Price(lane.slot0), principal, false); }
function laneSpread(anchor: bigint, feeBps: bigint, slippageBps: bigint, exactIn: boolean): readonly [bigint, bigint] { const fee = exactIn ? quoteLaneExactInFee(anchor, feeBps) : quoteLaneExactOutFee(anchor, feeBps); const totalBps = checkedAdd(feeBps, slippageBps); const total = exactIn ? quoteLaneExactInFee(anchor, totalBps) : quoteLaneExactOutFee(anchor, totalBps); return [fee, checkedSub(total, fee)]; }
function assembleQuote(state: QuoteState, request: QuoteRequest, feeAsset: Address, anchor: bigint, fee: bigint, slippageAmount: bigint): QuoteOutcome { const totalSpread = checkedAdd(fee, slippageAmount); let amountIn: bigint; let amountOut: bigint; if (request.mode === "ExactIn") { if (totalSpread >= anchor) return { kind: "Unavailable", reason: { kind: "SpreadConsumesAnchor" } }; amountIn = request.amount; amountOut = checkedSub(anchor, totalSpread); } else { amountIn = checkedAdd(anchor, totalSpread); amountOut = request.amount; } const [partner, treasury] = splitFee(anchor, fee, partnerFee(state, request.router, feeAsset)); return { kind: "Available", result: { amountIn, amountOut, feeAsset, feeAmount: fee, partnerFee: partner, treasuryFee: treasury } }; }
function directQuote(state: QuoteState, request: QuoteRequest, laneAsset: Address, lane: LaneState, cashToAsset: boolean, feeAsset: Address): QuoteOutcome { const anchor = request.mode === "ExactIn" ? quoteLaneExactIn(laneSlot0Price(lane.slot0), request.amount, cashToAsset) : quoteLaneExactOut(laneSlot0Price(lane.slot0), request.amount, cashToAsset); if (anchor === 0n) return { kind: "Unavailable", reason: { kind: "ZeroAnchor" } }; const principal = principalCashValue(state, laneAsset, lane); if (principal === 0n) return { kind: "Unavailable", reason: { kind: "ZeroPrincipal", asset: laneAsset } }; const rawFee = cashToAsset ? laneSlot0AskFeeBps(lane.slot0) : laneSlot0BidFeeBps(lane.slot0); const feeBps = calculateFeeBpsForRouter(state.whitelist.get(request.router) ?? false, state.blacklistFeeMultiplier, rawFee); const swapCash = cashToAsset ? request.mode === "ExactIn" ? request.amount : anchor : request.mode === "ExactIn" ? anchor : request.amount; const slippage = quoteLaneSlippageBps(swapCash, principal, lane.slippageKBps); const [fee, slippageAmount] = laneSpread(anchor, feeBps, slippage, request.mode === "ExactIn"); return assembleQuote(state, request, feeAsset, anchor, fee, slippageAmount); }
function routeQuote(state: QuoteState, request: QuoteRequest, inputLane: LaneState, outputLane: LaneState): QuoteOutcome { let intermediateCash: bigint; let anchor: bigint; if (request.mode === "ExactIn") { intermediateCash = quoteLaneExactIn(laneSlot0Price(inputLane.slot0), request.amount, false); anchor = quoteLaneExactIn(laneSlot0Price(outputLane.slot0), intermediateCash, true); } else { intermediateCash = quoteLaneExactOut(laneSlot0Price(outputLane.slot0), request.amount, true); anchor = quoteLaneExactOut(laneSlot0Price(inputLane.slot0), intermediateCash, false); } if (anchor === 0n) return { kind: "Unavailable", reason: { kind: "ZeroAnchor" } }; const firstPrincipal = principalCashValue(state, request.assetIn, inputLane); if (firstPrincipal === 0n) return { kind: "Unavailable", reason: { kind: "ZeroPrincipal", asset: request.assetIn } }; const secondPrincipal = principalCashValue(state, request.assetOut, outputLane); if (secondPrincipal === 0n) return { kind: "Unavailable", reason: { kind: "ZeroPrincipal", asset: request.assetOut } }; const weightedK = quoteLaneWeightedSlippageKBps(firstPrincipal, inputLane.slippageKBps, secondPrincipal, outputLane.slippageKBps); const slippage = quoteLaneSlippageBps(intermediateCash, checkedAdd(firstPrincipal, secondPrincipal), weightedK); const whitelisted = state.whitelist.get(request.router) ?? false; const bid = calculateFeeBpsForRouter(whitelisted, state.blacklistFeeMultiplier, laneSlot0BidFeeBps(inputLane.slot0)); const ask = calculateFeeBpsForRouter(whitelisted, state.blacklistFeeMultiplier, laneSlot0AskFeeBps(outputLane.slot0)); const feeBps = checkedAdd(bid, ask); const fee = request.mode === "ExactIn" ? quoteLaneExactInFee(anchor, feeBps) : quoteLaneExactOutFee(anchor, feeBps); const totalBps = checkedAdd(checkedAdd(bid, slippage), checkedAdd(ask, slippage)); const total = request.mode === "ExactIn" ? quoteLaneExactInFee(anchor, totalBps) : quoteLaneExactOutFee(anchor, totalBps); const feeAsset = request.mode === "ExactIn" ? request.assetOut : request.assetIn; return assembleQuote(state, request, feeAsset, anchor, fee, checkedSub(total, fee)); }

export function quote(request: QuoteRequest, context: QuoteContext, state: QuoteState): QuoteOutcome { assertU256(request.amount, "amount"); assertU256(context.executionBlockNumber, "executionBlockNumber"); if (state.cash !== context.cash) throw new QuoteError("CASH_MISMATCH", "state snapshot cash does not match context"); if (state.stateVersion !== context.stateVersion) throw new QuoteError("STATE_VERSION_MISMATCH", "state snapshot version does not match context"); if (request.amount === 0n) return { kind: "Unavailable", reason: { kind: "ZeroAmount" } }; if (request.assetIn.toLowerCase() === request.assetOut.toLowerCase()) return { kind: "Unavailable", reason: { kind: "EqualAssets" } }; const feeAsset = request.mode === "ExactIn" ? request.assetOut : request.assetIn; if (request.assetOut === context.cash) { const lane = laneOrReason(state, request.assetIn, context); return "kind" in lane ? { kind: "Unavailable", reason: lane } : directQuote(state, request, request.assetIn, lane, false, feeAsset); } if (request.assetIn === context.cash) { const lane = laneOrReason(state, request.assetOut, context); return "kind" in lane ? { kind: "Unavailable", reason: lane } : directQuote(state, request, request.assetOut, lane, true, feeAsset); } const input = laneOrReason(state, request.assetIn, context); if ("kind" in input) return { kind: "Unavailable", reason: input }; const output = laneOrReason(state, request.assetOut, context); if ("kind" in output) return { kind: "Unavailable", reason: output }; return routeQuote(state, request, input, output); }
export function quoteExactIn(request: QuoteRequest, context: QuoteContext, state: QuoteState): QuoteOutcome { return quote({ ...request, mode: "ExactIn" }, context, state); }
export function quoteExactOut(request: QuoteRequest, context: QuoteContext, state: QuoteState): QuoteOutcome { return quote({ ...request, mode: "ExactOut" }, context, state); }
export function solidityExactInAmount(outcome: QuoteOutcome): bigint { return outcome.kind === "Available" ? outcome.result.amountOut : 0n; }
export function solidityExactOutAmount(outcome: QuoteOutcome): bigint { return outcome.kind === "Available" ? outcome.result.amountIn : (1n << 256n) - 1n; }
export function solidityExactOutAmountForRequest(request: QuoteRequest, outcome: QuoteOutcome): bigint { return request.amount === 0n ? 0n : solidityExactOutAmount(outcome); }
