import { parseAbi } from "viem";

/** Actor function/event surface plus every Core and linked-library error it can receive. */
export const CORE_ACTOR_ABI = parseAbi([
  "function cash() view returns (address)",
  "function paused() view returns (bool)",
  "function lane(address asset) view returns (bytes32)",
  "function reserves(address asset) view returns (uint128 assetReserve, uint128 treasuryFees, uint128 partnerFees, uint128 escrowedAssets, uint128 totalPrincipalAmount)",
  "function quoteExactIn(uint256 amountIn, address assetIn, address assetOut) view returns (uint256 amountOut)",
  "function swapExactIn((address assetIn, address assetOut, address recipient, uint256 amountIn, uint256 amountOutMinimum, uint256 deadline) params) payable returns (uint256 amountOut)",
  "event SwapExecuted(address indexed router, address indexed assetIn, address indexed assetOut, bool exactIn, uint256 amountIn, uint256 amountOut, address feeAsset, uint256 feeAmount, uint256 partnerFee, uint256 treasuryFee)",
  "error AlreadyInitialized()",
  "error CashAssetDepositUnsupported()",
  "error EnforcedPause()",
  "error ExcessiveAmountIn()",
  "error ExpectedPause()",
  "error InsufficientAmountOut()",
  "error InvalidOperatorConfig()",
  "error InvalidSwapRecipient()",
  "error LaneNotPaused(address asset)",
  "error LpPositionNotFound()",
  "error NativePermitUnsupported()",
  "error NewOwnerIsZeroAddress()",
  "error NoHandoverRequest()",
  "error OperatorUnauthorized(address account)",
  "error Partner__UnauthorizedOperator()",
  "error PermitTokenMismatch()",
  "error PositionCallerUnauthorized()",
  "error Reentrancy()",
  "error SwapDeadlineExpired()",
  "error Unauthorized()",
  "error UnauthorizedCallContext()",
  "error UnexpectedNativeDepositValue()",
  "error UnexpectedNativeSwapValue()",
  "error UpgradeFailed()",
  // Linked libraries execute in Core's context and can bubble errors absent from CoreUUPS.json.
  "error Core__SwapUnavailable()",
  "error LaneDoesNotExist(address assetIn, address assetOut)",
  "error Core__ReserveUnderflow()",
  "error Overflow()",
  "error FullMulDivFailed()",
  "error MulDivFailed()",
  "error TransferFromFailed()",
  "error TransferFailed()",
]);

/** ERC-20 plus the permissionless LunarBase test token mint surface. */
export const MOCK_TOKEN_ABI = parseAbi([
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function decimals() view returns (uint8)",
  "function MINT_AMOUNT() view returns (uint256)",
  "function mint(address to)",
  "function balanceOf(address account) view returns (uint256)",
  "function allowance(address owner, address spender) view returns (uint256)",
  "function approve(address spender, uint256 value) returns (bool)",
  "error ERC20InsufficientAllowance(address spender, uint256 allowance, uint256 needed)",
  "error ERC20InsufficientBalance(address sender, uint256 balance, uint256 needed)",
  "error ERC20InvalidApprover(address approver)",
  "error ERC20InvalidReceiver(address receiver)",
  "error ERC20InvalidSender(address sender)",
  "error ERC20InvalidSpender(address spender)",
]);
